name: "Hello Actions temptemp"
description: "Greet someone again"
author: "rikard@testahlsell.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
