name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/action_a
        with:
          MY_NAMES: "Rikard"
          MY_OCCU: "Data Scientist"
      - uses: ./.github/actions/action_b
        with:
          MY_NAME: "Mona-Lisa"