name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/action_a
        with:
          MY_NAMES: "Rikard"
          MY_OCCU: "Data Scientist"
      - uses: ./.github/actions/action_b
        with:
          MY_NAME: "Mona-Lisa"

  rikardtest:    
    name: Hello world action 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/action_a
        with:
          MY_NAMES: "Rikard"
          MY_OCCU: "Data Scientist"
      - uses: ./.github/actions/action_b
        with:
          MY_NAME: "Mona-Lisa"

  installpython:
    name: Install python libraries from requirements.txt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/requirements.txt
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash