name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/action_a
        with:
          MY_NAMES: "Något annat"
          MY_OCCU: "Bilmekaniker"
      - uses: ./.github/actions/action_b
        with:
          MY_NAME: "Afro da third"